-- Run this entire script in your Supabase SQL Editor to add the Careers features

-- 1. Create the Careers Table
CREATE TABLE IF NOT EXISTS careers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT NOT NULL,
  location TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE careers ENABLE ROW LEVEL SECURITY;

-- 3. Allow public read access (so the website can fetch the jobs)
CREATE POLICY "Public careers are viewable by everyone."
  ON careers FOR SELECT
  USING ( true );

-- 4. Allow authenticated admins full access
CREATE POLICY "Admins can insert careers."
  ON careers FOR INSERT
  WITH CHECK ( true );

CREATE POLICY "Admins can update careers."
  ON careers FOR UPDATE
  USING ( true );

CREATE POLICY "Admins can delete careers."
  ON careers FOR DELETE
  USING ( true );
