-- SQL Schema for Supabase

-- Portfolio Table
CREATE TABLE portfolio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  tag TEXT NOT NULL,
  image_url TEXT NOT NULL,
  client TEXT,
  year TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Blogs Table
CREATE TABLE blogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  excerpt TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT NOT NULL,
  read_time TEXT,
  image_url TEXT NOT NULL,
  date TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Careers Table
CREATE TABLE careers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT NOT NULL,
  location TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Policies (Optional, but recommended for security if accessing directly from frontend)
-- Enable Row Level Security
ALTER TABLE portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE careers ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Public profiles are viewable by everyone."
  ON portfolio FOR SELECT
  USING ( true );

CREATE POLICY "Public blogs are viewable by everyone."
  ON blogs FOR SELECT
  USING ( true );

CREATE POLICY "Public careers are viewable by everyone."
  ON careers FOR SELECT
  USING ( true );

-- Allow authenticated users (admin) full access
CREATE POLICY "Admins can insert portfolio."
  ON portfolio FOR INSERT
  WITH CHECK ( true );

CREATE POLICY "Admins can update portfolio."
  ON portfolio FOR UPDATE
  USING ( true );

CREATE POLICY "Admins can delete portfolio."
  ON portfolio FOR DELETE
  USING ( true );

CREATE POLICY "Admins can insert blogs."
  ON blogs FOR INSERT
  WITH CHECK ( true );

CREATE POLICY "Admins can update blogs."
  ON blogs FOR UPDATE
  USING ( true );

CREATE POLICY "Admins can delete blogs."
  ON blogs FOR DELETE
  USING ( true );

CREATE POLICY "Admins can insert careers."
  ON careers FOR INSERT
  WITH CHECK ( true );

CREATE POLICY "Admins can update careers."
  ON careers FOR UPDATE
  USING ( true );

CREATE POLICY "Admins can delete careers."
  ON careers FOR DELETE
  USING ( true );

-- Allow public access to media bucket
CREATE POLICY "Public media uploads"
ON storage.objects FOR INSERT TO public
WITH CHECK ( bucket_id = 'media' );

CREATE POLICY "Public media viewing"
ON storage.objects FOR SELECT TO public
USING ( bucket_id = 'media' );

CREATE POLICY "Public media deletes"
ON storage.objects FOR DELETE TO public
USING ( bucket_id = 'media' );
